### ISSUE TITLE
Error on script runing in master

### ISSUE THREAD

**Issue by angolini** [Freescale/Documentation#23]
$ repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b master
$ repo sync
$ repo start --all master
$ ./bitbake-metadata2doc.sh  ~/yocto/master/ ~/gitdm/ jethro master

```
Welcome to Freescale Community BSP

The Yocto Project has extensive documentation about OE including a
reference manual which can be found at:
    http://yoctoproject.org/documentation

For more information about OpenEmbedded see their website:
    http://www.openembedded.org/

You can now run 'bitbake <target>'

Common targets are:
    core-image-minimal
    meta-toolchain
    meta-toolchain-sdk
    adt-installer
    meta-ide-support

Your configuration files at tmp.CAF0wjk9OP have not been touched.
Parsing recipes..ERROR: No IMAGE_CMD defined for IMAGE_FSTYPES entry 'barebox.mxsboot-sdcard' - possibly invalid type name or missing support class
ERROR: Failed to parse recipe: ~/yocto/master/sources/meta-fsl-arm/recipes-fsl/images/fsl-image-mfgtool-initramfs.bb
Traceback (most recent call last):
  File "~/yocto/master/sources/Documentation/scripts/extract-bitbake-metadata.py", line 333, in <module>
    data.update(extract_bitbake_metadata(user_recipes))
  File "~/yocto/master/sources/Documentation/scripts/extract-bitbake-metadata.py", line 290, in extract_bitbake_metadata
    tinfoil.parseRecipes()
  File "~/yocto/master/sources/poky/bitbake/bin/../lib/bb/tinfoil.py", line 68, in parseRecipes
    self.cooker.updateCache()
  File "~/yocto/master/sources/poky/bitbake/bin/../lib/bb/cooker.py", line 1557, in updateCache
    raise bb.BBHandledException()
bb.BBHandledException
ERROR: error extracting bitbake metadata for board 
```

I manually replaced the absolute path and used ~ instead.

**Comment by angolini** [comment]
I need to test it on latest. But I will close it right now. If needed I reopen the issue
